# This workflow will automatically create a new release and upload the default geometry

name: Create new release

on:
  push:
    tags:
    - "*v*.*.*"
    
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup gegede
      run: pip install git+https://github.com/brettviren/gegede.git@86ca28190516a23203cd883aafb0548a61664ceb
    - name: Setup
      run: pip install .
    - name: Build default gdml files
      run: ./build_hall.sh
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nd_hall_with_lar_tms_sand.gdml
          anti_fiducial_nd_hall_with_lar_tms_sand.gdml
        body: See `CHANGELOG.md` for a detailed release history.
